// **
// Consider the following assembly code:
//
// long loop(long x, int n)
// x in %rdi, n in %esi
// loop:
//   movl   %esi, %ecx
//   movl   $1, %edx
//   movl   $0, %eax
//   jmp    .L2
// .L3:
//   movq   %rdi, %r8
//   andq   %rdx, %r8
//   orq    %r8, %rax
//   salq   %cl, %rdx
// .L2
//   testq  %rdx, %rdx
//   jne    .L3
//   rep; ret
//
// The proceding code was generated by compiling C code that had the following
// overall form:
//
// long loop(long x, long n)
// {
//     long result = _________;
//     long mask;
//     for (mask = _________; mask  _________ ; mask = _________) {
//         result |= _________ ;
//     }
//     return result;
// }
//
//     Your task is to fill in the missing parts of the C code to get a program
// equivalent to the generated assembly code. Recall that the result of the
// function is returned in the register %rax. You will find it helpful to
// examine the assembly code before, during, and after the loop to form a
// consistent mapping between the registers and the program variables.
//
//  A. Which registers hold program values x, n, result, and mask?
//  B. What are the initial values of result and mask?
//  C. What is the test condition for mask?
//  D. How does mask get updated?
//  E. How does result get updated?
//  F. Fill in all the missing parts of the C code.

long loop(long x, long n) {
    long result = 0;
    long mask;
    for (mask = 1; mask; mask = mask >> n) {
        result |= x & mask;
    }
    return result;
}

//  A. %rdi holds x, %esi holds n, %rax holds result, %rdx holds mask.
//  B. The initial values of result and mask are 0 and 1.
//  C. testq %rdx, %rdx; which will set ZF when %rdx is 0.
//  D. salq %cl, %rdx; where %cl holds n, so mask will >>= n in each iteration.
//  E. movq %rdi, %r8; andq %rdx, %r8; orq %r8, %rax; where %rdi holds x, and
//     %rdx holds mask, so result will |= x & mask in each iteration.
